# Generated by Django 6.0.3 on 2026-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='iso_code',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
